# Generated by Django 4.0.3 on 2022-03-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Beehyv', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopingItem',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='author',
        ),
    ]
